### ISSUE TITLE
I am a User and I want to see my comments and up-/down-votes without a full page-reload.

### ISSUE THREAD

**Issue by kr89** [spicy-memes17/enterprise-memes#55]
Dynamisches laden von Inhalten auf der Seite.
Minimum:
-Eigene Kommentare
-Eigene Votes

Mögliche Zusätzliche Features, falls problemlos umsetzbar:
-Andere Kommentare
-Andere Votes
-Memes 
-Aktualisierungen

**Comment by mbrodmann** [comment]
merged on master -> done
